name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.100-preview.7.25322.101
          dotnet-quality: 'preview'
          source-url: https://nuget.pkg.github.com/YAS-SIIN/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: ./restore.sh

      # Step 4: Build the project
      - name: Build
        run: ./build.sh

      # Step 5: Pack the project
      - name: Pack
        run: dotnet pack src/EFCore.SharePoint/EFCore.SharePoint.csproj --configuration Release -o ./packages

      # Step 6: Publish package to GitHub Packages
      - name: Publish to GitHub Packages
        run: dotnet nuget push ./packages/*.nupkg --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
