name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: ./restore.sh

      # Step 4: Build the project
      - name: Build
        run: ./build.sh

      # Step 5: Pack the project
      - name: Pack
        run: dotnet pack src/EFCore.SharePoint/EFCore.SharePoint.csproj --configuration Release -o ./packages

      # Step 6: Publish package to GitHub Packages
      - name: Publish to GitHub Packages
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.FOR_NUGETPACKAGE }} --source "https://nuget.pkg.github.com/YAS-SIIN/index.json" --skip-duplicate
